global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:5001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user:5002']
